apiVersion: v1
kind: Pod

metadata:
  name: storage-test

spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: ebs-storage

  volumes:
  - name: ebs-storage
    persistentVolumeClaim:
      claimName: ebs-pvc
